config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  get 'signup', to: 'users#new'
  get 'account', to: 'users#show'
  get 'news', to: 'users#news'
  get 'followed/:id', to: 'users#followed', as: 'followed'
  post 'users/create'

  get 'login', to: 'sessions#new'
  post 'sessions/create'
  delete 'sessions/destroy', as: :logout

  get 'posts/index'
  resources :posts do
    resources :comments, only: [:create]
  end

  post 'subscriptions/create'
  delete 'subscriptions/destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, uniqueness: true, presence: true
  validates :content, presence: true
end

app/models/session.rb
class Session < ApplicationRecord
  
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :follower, foreign_key: :follower_id, class_name: 'User'
  belongs_to :followed, foreign_key: :followed_id, class_name: 'User'

  validates :followed, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :subscriptions, foreign_key: 'follower_id'
  has_many :comments

  has_secure_password

  validates :fname, presence: true
  validates :lname, presence: true
  validates :email, presence: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: 'is incorrect' }, uniqueness: true
  validates :password, confirmation: true, length: { minimum: 8 }, presence: true
  validates :password_confirmation, presence: true

  def last_posted
    new_posts = [];
    self.subscriptions.each do |subscription|
      new_posts += subscription.followed.posts
    end

    return new_posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method [ :current_user, :post_date]

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def accept_logged
    if current_user.nil?
      puts 'unlogged'
      redirect_to login_path
      return false
    end
  end

  def post_date (post)
    datetime = Time.at(post.created_at).to_datetime
    time = datetime.to_time
    date = datetime.to_date
    return date.day.to_s + '/' + date.month.to_s + '/' + date.year.to_s + ' ' + time.hour.to_s + ':' + time.min.to_s + ':' + time.sec.to_s
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :accept_logged, only: [:create]

  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.create({ comment: params[:comment], post: @post })

    if @comment.save
      respond_to :js
    elsif
      respond_to do |format|
        format.js { render partial: '/show_errors', locals: { object: @comment } }
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :accept_logged, only: [:new, :create, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.create(params.require(:post).permit(:title, :content))

    if @post.save
      redirect_to account_url
    elsif
      respond_to do |format|
        format.js { render partial: '/show_errors', locals: { object: @post } }
      end
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])

    if @post.update(params.require(:post).permit(:title, :content))
      flash[:success] = 'Post successfully updated'
      redirect_to account_path
    elsif
      respond_to do |format|
        format.js { render partial: '/show_errors', locals: { object: @post } }
      end
    end
  end

  def destroy
    Post.find(params[:id]).destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :accept_logged, only: [:destroy]

  def new
    render 'users/login'
  end

  def create
    @user = User.find_by email: params[:auth][:email].downcase

    if !@user.nil? && BCrypt::Password.new(@user.password_digest) == params[:auth][:password]
      session[:user_id] = @user.id
      redirect_to posts_index_url, flash: { success: 'Login success' }
    elsif
      @user = User.new
      @user.errors[:base].push('Invalid email or password is present');
      respond_to do |format|
        format.js { render partial: '/show_errors', locals: { object: @user } }
      end
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_url, flash: { success: 'You have logged out' }
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :accept_logged, only: [:create, :destroy]

  def create
    @subscription = current_user.subscriptions.create(followed_id: params[:user_id])

    if @subscription.save
      respond_to do |format|
        format.js { render partial: 'subscribe', locals: { action: :unsubscribe, followed_id: params[:user_id] } }
      end
    end
  end

  def destroy
    if current_user.subscriptions.find_by(followed_id: params[:user_id]).destroy
      respond_to do |format|
        format.js { render partial: 'subscribe', locals: { action: :subscribe, followed_id: params[:user_id] } }
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :accept_logged, only: [:show, :news, :followed]

  def new
    @user = User.new
  end

  def create
     @user = User.new(params.require(:user).permit(:fname, :lname, :email, :password, :password_confirmation))

     if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'Account created'
      redirect_to posts_index_url
     elsif
      @user.errors.full_messages.each { |message| puts message }
      redirect_to posts_index_url
     end
  end

  def show
    @posts = current_user.posts
  end

  def news
    @posts = current_user.last_posted.sort_by { |post| post.created_at.to_i }.reverse
  end

  def followed
    @posts = Post.where(user_id: params[:id]).all
    @followed = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="post-comment rounded p-3 mt-3">
  <div class="comment-head">
    <img class="inline-block mr-3 rounded-circle" style="width: 35px" src="<%= image_path 'user_placeholder.jpg' %>" alt="">
    <%= comment.user.fname + ' ' + comment.user.lname %>
  </div>
  <div class="comment-time text-muted my-2">
    <small><%= post_date comment %></small>
  </div>
  <div class="comment-body">
    <%= comment.comment %>
  </div>
</div>

app/views/comments/create.js.erb
var comment = '<%= j render partial: 'comment', locals: { comment: @comment } %>'

$('.comments-list').append(comment);

$('.comment-form textarea').val('');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogcms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>

    <div class="bg-info">
      <div class="container px-0">
        <nav class="navbar navbar-expand-lg navbar-light bg-info">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <%= link_to 'Home', root_path, class: 'nav-link' %>
              </li>
            </ul>

            <ul class="navbar-nav float-lg-right">
              <% if current_user %>
                <li class="nav-item">
                  <%= link_to account_path, class: 'nav-link' do %>
                    <i class="far fa-user-circle mr-1"></i>
                    <%= current_user.fname %>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %>
                </li>
              <% elsif %>
                <li class="nav-item">
                  <%= link_to 'Login', login_path, class: 'nav-link' %>
                </li>
                <span class="navbar-text">or</span>
                <li class="nav-item">
                  <%= link_to 'Sign Up', signup_path, class: 'nav-link' %>
                </li>
              <% end %>
            </ul>
          </div>
        </nav>
      </div>
    </div>

    <div class="container application-wrapper">
      <% flash.each do |key, message| %>
        <div class="mt-3 alert alert-<%= key %>" role="alert">
          <%= message %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_post_form.html.erb
<%= form_with model: @post, data: { name: @post.class.name } do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: 'form-control', rows: 10 %>
  </div>
  <%= form.submit submit_title, class: 'btn btn-primary' %>
<% end %>

app/views/posts/_post_preview.html.erb
<% @posts.each do |post| %>
  <div class="card mt-3 index-post-preview post-preview" user-id="<%= post.user.id %>">
    <h5 class="card-header"><%= post.title %></h5>
    <div class="card-body">
      <h5 class="card-title">
        <img class="rounded-circle post-list-user-avatar mr-3" src="<%= image_path 'user_placeholder.jpg' %>" alt="">
        <%= post.user.fname + ' ' + post.user.lname %>

        <% if current_user && post.user.id != current_user.id %>
          <% if Subscription.where(follower_id: current_user.id, followed_id: post.user.id).present? %>
            <%= render partial: 'subscriptions/unsubscribe_button', locals: { user_id: post.user.id } %>
          <% elsif %>
            <%= render partial: 'subscriptions/subscribe_button', locals: { user_id: post.user.id } %>
          <% end %>
        <% end %>

      </h5>
      <p class="card-text"><%= post.content[0...500] + '...' %></p>
      <p class="card-text"><small class="text-muted"><%= post_date post %></small></p>
      <%= link_to 'Read More', post, class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/posts/destroy.js.erb
$('.index-post-preview[post-id=<%= params[:id] %>]').remove();

app/views/posts/edit.html.erb
<h3 class="my-3">Update post</h3>
<%= render 'post_form', submit_title: 'Update Post' %>

app/views/posts/index.html.erb
<%= render 'posts/post_preview', collection: @posts %>

app/views/posts/new.html.erb
<h3 class="my-3">Create a new post</h3>
<%= render 'post_form', submit_title: 'Save Post' %>

app/views/posts/show.html.erb
<div class="post-show mt-3 mb-5">
  <div class="username align-middle">
    <img class="inline-block mr-3 rounded-circle" src="<%= image_path 'user_placeholder.jpg' %>" alt="">
    <%= @post.user.fname + ' ' + @post.user.lname %>
  </div>

  <h3 class="mt-3"><%= @post.title %></h3>
  <span class="text-muted"><%= post_date @post %></span>

  <p class="mt-3"><%= @post.content %></p>

  <h3 class="mt-4">Comments</h3>
  <% if current_user %>
    <%= form_with model: @comment, url: post_comments_path(@post), data: { name: 'Comment' }, class: 'comment-form rounded bg-light p-3' do |form| %>
      <div class="form-group">
        <%= form.label 'Comment' %>
        <%= form.text_area :comment, class: 'form-control', placeholder: 'Type here', rows: 4 %>
      </div>
      <%= form.submit 'Leave comment', class: 'btn btn-primary' %>
    <% end %>
  <% end %>
  <div class="comments-list">
    <%= render partial: 'comments/comment', collection: @post.comments %>
  </div>
</div>

app/views/subscriptions/_subscribe.js.erb
var subButton = $('<%= render partial: action.to_s + '_button', locals: { :user_id => followed_id } %>');

if ($('.post-preview').length > 0)
  $('.post-preview[user-id=<%= followed_id %>]').find('.user-subscribe-button').replaceWith(subButton);
else
  $('.user-subscribe-button').replaceWith(subButton);

app/views/subscriptions/_subscribe_button.html.erb
<%= button_to 'Subscribe', { controller: :subscriptions, action: :create, user_id: user_id }, remote: true, class: 'btn btn-outline-primary ml-2 btn-sm', form_class: 'd-inline-block user-subscribe-button', type: 'button' %>

app/views/subscriptions/_unsubscribe_button.html.erb
<%= button_to 'Unsubscribe', { controller: :subscriptions, action: :destroy, user_id: user_id }, method: :delete, remote: true, class: 'btn btn-outline-success ml-2 btn-sm', form_class: 'd-inline-block user-subscribe-button', type: 'button' %>

app/views/users/_side_menu.html.erb
<div class="col-lg-3">
  <div class="account-side-menu bg-light rounded">
    <%= link_to account_path, class: 'user-data text-center p-3 d-link' do %>
      <img class="rounded-circle w-50 d-inline-block" src="<%= image_path 'user_placeholder.jpg' %>" alt="">
      <p class="d-inline-blcok mt-3 h4"><%= current_user.fname + ' ' + current_user.lname %></p>
    <% end %>
    <div class="m-2">
      <%= link_to 'New Post', new_post_path, class: 'btn btn-primary btn-block' %>
    </div>
    <% if current_user.subscriptions.present? %>
      <div class="subscriptions-list mt-1">
        <div class="title p-2">Subscriptions</div>
        <%= link_to 'All new posts', news_path, class: 'title p-2 mb-2 d-block' %>
        <% current_user.subscriptions.each do |subscription| %>
          <%= link_to followed_path(subscription.followed_id), class: 'subscription align-middle p-2 d-block' do %>
            <img class="rounded-circle w-25 d-inline-block mr-2" src="<%= image_path 'user_placeholder.jpg' %>" alt="">
            <%= subscription.followed.fname + ' ' + subscription.followed.lname %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followed.html.erb
<div class="row mt-3">
  <%= render 'side_menu' %>
  <div class="col-lg-9">
    <img class="rounded-circle mr-3" style="width: 45px" src="<%= image_path 'user_placeholder.jpg' %>" alt="">
    <%= @followed.fname + ' ' + @followed.lname %>
    <%= button_to 'Unsubscribe', { controller: :subscriptions, action: :destroy, user_id: @followed.id }, method: :delete, remote: true, class: 'btn btn-outline-success ml-2 btn-sm', form_class: 'd-inline-block user-subscribe-button', type: 'button' %>
    <div class="rounded">
      <% @posts.each do |post| %>
        <div class="card mt-3 index-post-preview" user-id="<%= post.user.id %>">
          <h5 class="card-header"><%= post.title %></h5>
          <div class="card-body">
            <p class="card-text"><%= post.content[0...500] + '...' %></p>
            <p class="card-text"><small class="text-muted"><%= post_date post %></small></p>
            <%= link_to 'Read More', post, class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/login.html.erb
<div id="login-input-wrap">
  <h3 class="text-center">Log In</h3>
  <%= form_for :auth, url: sessions_create_path, remote: true, data: { name: 'User' } do |form| %>
  <div class="form-group">
      <%= form.label :email, 'Email' %>
      <%= form.text_field :email, class: 'form-control', placeholder: 'example@gmail.com' %>
    </div>
    <div class="form-group">
      <%= form.label :password, 'Password' %>
      <%= form.password_field :password, class: 'form-control', placeholder: '********' %>
    </div>
    <span>or </span><%= link_to 'Sign Up', signup_path %>
    <div class="text-center">
      <%= submit_tag 'Log In', class: 'btn btn-primary btn-lg' %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div id="login-input-wrap">
  <h3 class="text-center">Sign Up</h3>
  <%= form_with model: @user, url: users_create_path do |form| %>
    <div class="form-group">
      <%= form.label :fname, 'First name' %>
      <%= form.text_field :fname, class: 'form-control', placeholder: 'John' %>
    </div>
    <div class="form-group">
      <%= form.label :lname, 'Last name' %>
      <%= form.text_field :lname, class: 'form-control', placeholder: 'Davis' %>
    </div>
    <div class="form-group">
      <%= form.label :email, 'Email' %>
      <%= form.text_field :email, class: 'form-control', placeholder: 'example@gmail.com' %>
    </div>
    <div class="form-group">
      <%= form.label :password, 'Password' %>
      <%= form.password_field :password, class: 'form-control', placeholder: '********' %>
    </div>
    <div class="form-group">
      <%= form.label :password_confirmation, 'Password confirmation' %>
      <%= form.password_field :password_confirmation, class: 'form-control', placeholder: '********' %>
    </div>
    <span>or </span><%= link_to 'Login', login_path %>
    <div class="text-center">
      <%= form.submit 'Sign Up', class: 'btn btn-primary btn-lg' %>
    </div>
  <% end %>
</div>

app/views/users/news.html.erb
<div class="row mt-3">
  <%= render 'side_menu' %>
  <div class="col-lg-9">
    <div class="rounded">
      <h4>New Posts</h4>
      <%= render 'posts/post_preview', collection: @posts %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row mt-3">
  <%= render 'side_menu' %>
  <div class="col-lg-9">
    <div class="rounded">
      <h4>My posts</h4>
      <% @posts.each do |post| %>
        <div class="card mt-3 index-post-preview" user-id="<%= post.user.id %>" post-id="<%= post.id %>">
          <h5 class="card-header"><%= post.title %></h5>
          <div class="card-body">
            <p class="card-text"><%= post.content[0...500] + '...' %></p>
            <p class="card-text"><small class="text-muted"><%= post_date post %></small></p>
            <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-primary mr-2' %>
            <%= link_to 'Delete', post_path(post), method: 'delete', remote: true, class: 'btn btn-danger', data: { confirm: 'Are you sure?', disable_with: 'Deleting...' } %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>